[package]
name = "your-username/your-project-name"
version = "0.1.0"
description = "My Next.js app running on Wasmer"

[dependencies]
"wasmer/node" = "20.12.2"

[[command]]
name = "start"
module = "wasmer/node"
runner = "https://webc.org/command/node"

[command.annotations.wasi]
main-args = [
    "npm",
    "start",
]
