
[package]
name = "firebase-studio/your-project-name-static"
version = "0.1.0"
description = "My Next.js app running on Wasmer"

[[command]]
name = "start"
module = "wasmer/node:20.12.2"
runner = "https"

[command.annotations]
run = "npm run start"
build = "npm ci && npm run build"
